events {}

http {
    server {
        listen  8080;
        root    /usr/share/nginx/html;
    }
    types {
        text/css            css;
        text/html           html;
        text/javascript     js;
    }
}
