sonar.projectKey=Linus-nisse-segmentering_Agile-Linus
sonar.organization=Linus-nisse-segmentering
sonar.projectName=Agile-Linus
sonar.sourceEncoding=UTF-8

sonar.sources=backend
sonar.tests=backend/spec
sonar.test.inclusions=backend/spec/**/*_spec.rb

sonar.exclusions=coverage/**,node_modules/**,vendor/**,static/swagger-ui/**,monitoring/**,docs/**,.github/**,yml/**,tmp/**,backend/database/schema*.sql,backend/database/seeds.sql,**/*.min.js

sonar.ruby.coverage.reportPaths=backend/coverage/.resultset.json
