sonar.projectKey=Linus-nisse-segmentering_Agile-Linus
sonar.organization=Linus-nisse-segmentering
sonar.projectName=Agile-Linus
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=spec
sonar.test.inclusions=spec/**/*_spec.rb

sonar.exclusions=coverage/**,node_modules/**,vendor/**,static/swagger-ui/**,monitoring/**,docs/**,.github/**,yml/**,tmp/**,db/schema*.sql,db/seeds.sql,**/*.min.js

sonar.ruby.coverage.reportPaths=coverage/.resultset.json