global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "backend"
    static_configs:
      # When deployed across VMs, scrape the backend app directly via private DNS
      - targets: ["backend.backend.internal:1010"]
    metrics_path: /metrics